package com.revature.Entity;
// we will make an account object
// in sql we will have account table and add something to combine them, maybe an account number that combines the to its autogenerated
/*
in user creation maybe and then
when we make an user id we will autogenerate and account number

if an account type doesn't exist
how do i not have to manually type the username when making account
 */

//to do section
/*
TODO:make the login change menus:in works
TODO:make an account model:done
Todo:figure out when you make an account how to link it to the persisting user in sql and java:in the works
todo:figure out the sql for account to defualt on the values we need: done
 */

//current playground section
/*
private static void postLoginMenu(*figure out the parameters*) {
        while (something is true) {
            System.out.println("What would you like to do?");
            System.out.println("1. Create an account");
            System.out.println("2. View accounts");
            System.out.println("0. Logout");
            int choice = scanner.nextInt();
            scanner.nextLine();  // Consume newline

            switch (choice) {
                case 1:
                    accountController.createAccount();
                    break;
                case 2:
                    accountController.viewAccounts();
                    break;
                case 0:
                    return;  // Logout
                default:
                    System.out.println("Invalid choice. Please try again.");
            }
        }
    }
}
 */

