package com.revature.Entity;
// we will make an account object
// in sql we will have account table and add something to combine them, maybe an account number that combines the to its autogenerated
/*
in user creation maybe and then
 */